tabWidth: 2
useTabs: false
semi: true
singleQuote: true
jsxSingleQuote: true
trailingComma: 'none'
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: 'avoid'
proseWrap: 'never'
htmlWhitespaceSensitivity: 'ignore'
